import { v4 as uuidv4 } from "uuid";
export const countries = [
  { id: uuidv4(), value: "Afghanistan", label: "Afghanistan" },
  { id: uuidv4(), value: "Åland Islands", label: "Åland Islands" },
  { id: uuidv4(), value: "Albania", label: "Albania" },
  { id: uuidv4(), value: "Algeria", label: "Algeria" },
  { id: uuidv4(), value: "American Samoa", label: "American Samoa" },
  { id: uuidv4(), value: "Andorra", label: "Andorra" },
  { id: uuidv4(), value: "Angola", label: "Angola" },
  { id: uuidv4(), value: "Anguilla", label: "Anguilla" },
  { id: uuidv4(), value: "Antarctica", label: "Antarctica" },
  { id: uuidv4(), value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
  { id: uuidv4(), value: "Argentina", label: "Argentina" },
  { id: uuidv4(), value: "Armenia", label: "Armenia" },
  { id: uuidv4(), value: "Aruba", label: "Aruba" },
  { id: uuidv4(), value: "Australia", label: "Australia" },
  { id: uuidv4(), value: "Austria", label: "Austria" },
  { id: uuidv4(), value: "Azerbaijan", label: "Azerbaijan" },
  { id: uuidv4(), value: "Bahamas", label: "Bahamas" },
  { id: uuidv4(), value: "Bahrain", label: "Bahrain" },
  { id: uuidv4(), value: "Bangladesh", label: "Bangladesh" },
  { id: uuidv4(), value: "Barbados", label: "Barbados" },
  { id: uuidv4(), value: "Belarus", label: "Belarus" },
  { id: uuidv4(), value: "Belgium", label: "Belgium" },
  { id: uuidv4(), value: "Belize", label: "Belize" },
  { id: uuidv4(), value: "Benin", label: "Benin" },
  { id: uuidv4(), value: "Bermuda", label: "Bermuda" },
  { id: uuidv4(), value: "Bhutan", label: "Bhutan" },
  { id: uuidv4(), value: "Bolivia", label: "Bolivia" },
  {
    id: uuidv4(),
    value: "Bosnia and Herzegovina",
    label: "Bosnia and Herzegovina",
  },
  { id: uuidv4(), value: "Botswana", label: "Botswana" },
  { id: uuidv4(), value: "Bouvet Island", label: "Bouvet Island" },
  { id: uuidv4(), value: "Brazil", label: "Brazil" },
  {
    id: uuidv4(),
    value: "British Indian Ocean Territory",
    label: "British Indian Ocean Territory",
  },
  { id: uuidv4(), value: "Brunei Darussalam", label: "Brunei Darussalam" },
  { id: uuidv4(), value: "Bulgaria", label: "Bulgaria" },
  { id: uuidv4(), value: "Burkina Faso", label: "Burkina Faso" },
  { id: uuidv4(), value: "Burundi", label: "Burundi" },
  { id: uuidv4(), value: "Cambodia", label: "Cambodia" },
  { id: uuidv4(), value: "Cameroon", label: "Cameroon" },
  { id: uuidv4(), value: "Canada", label: "Canada" },
  { id: uuidv4(), value: "Cape Verde", label: "Cape Verde" },
  { id: uuidv4(), value: "Cayman Islands", label: "Cayman Islands" },
  {
    id: uuidv4(),
    value: "Central African Republic",
    label: "Central African Republic",
  },
  { id: uuidv4(), value: "Chad", label: "Chad" },
  { id: uuidv4(), value: "Chile", label: "Chile" },
  { id: uuidv4(), value: "China", label: "China" },
  { id: uuidv4(), value: "Christmas Island", label: "Christmas Island" },
  {
    id: uuidv4(),
    value: "Cocos (Keeling) Islands",
    label: "Cocos (Keeling) Islands",
  },
  { id: uuidv4(), value: "Colombia", label: "Colombia" },
  { id: uuidv4(), value: "Comoros", label: "Comoros" },
  { id: uuidv4(), value: "Congo", label: "Congo" },
  {
    id: uuidv4(),
    value: "Congo, The Democratic Republic of The",
    label: "Congo, The Democratic Republic of The",
  },
  { id: uuidv4(), value: "Cook Islands", label: "Cook Islands" },
  { id: uuidv4(), value: "Costa Rica", label: "Costa Rica" },
  { id: uuidv4(), value: "Cote D'ivoire", label: "Cote D'ivoire" },
  { id: uuidv4(), value: "Croatia", label: "Croatia" },
  { id: uuidv4(), value: "Cuba", label: "Cuba" },
  { id: uuidv4(), value: "Cyprus", label: "Cyprus" },
  { id: uuidv4(), value: "Czech Republic", label: "Czech Republic" },
  { id: uuidv4(), value: "Denmark", label: "Denmark" },
  { id: uuidv4(), value: "Djibouti", label: "Djibouti" },
  { id: uuidv4(), value: "Dominica", label: "Dominica" },
  { id: uuidv4(), value: "Dominican Republic", label: "Dominican Republic" },
  { id: uuidv4(), value: "Ecuador", label: "Ecuador" },
  { id: uuidv4(), value: "Egypt", label: "Egypt" },
  { id: uuidv4(), value: "El Salvador", label: "El Salvador" },
  { id: uuidv4(), value: "Equatorial Guinea", label: "Equatorial Guinea" },
  { id: uuidv4(), value: "Eritrea", label: "Eritrea" },
  { id: uuidv4(), value: "Estonia", label: "Estonia" },
  { id: uuidv4(), value: "Ethiopia", label: "Ethiopia" },
  {
    id: uuidv4(),
    value: "Falkland Islands (Malvinas)",
    label: "Falkland Islands (Malvinas)",
  },
  { id: uuidv4(), value: "Faroe Islands", label: "Faroe Islands" },
  { id: uuidv4(), value: "Fiji", label: "Fiji" },
  { id: uuidv4(), value: "Finland", label: "Finland" },
  { id: uuidv4(), value: "France", label: "France" },
  { id: uuidv4(), value: "French Guiana", label: "French Guiana" },
  { id: uuidv4(), value: "French Polynesia", labe: "French Polynesia" },
  {
    id: uuidv4(),
    value: "French Southern Territories",
    labe: "French Southern Territories",
  },
  { id: uuidv4(), value: "Gabon", label: "Gabon" },
  { id: uuidv4(), value: "Gambia", label: "Gambia" },
  { id: uuidv4(), value: "Georgia", label: "Georgia" },
  { id: uuidv4(), value: "Germany", label: "Germany" },
  { id: uuidv4(), value: "Ghana", label: "Ghana" },
  { id: uuidv4(), value: "Gibraltar", label: "Gibraltar" },
  { id: uuidv4(), value: "Greece", label: "Greece" },
  { id: uuidv4(), value: "Greenland", label: "Greenland" },
  { id: uuidv4(), value: "Grenada", label: "Grenada" },
  { id: uuidv4(), value: "Guadeloupe", label: "Guadeloupe" },
  { id: uuidv4(), value: "Guam", label: "Guam" },
  { id: uuidv4(), value: "Guatemala", label: "Guatemala" },
  { id: uuidv4(), value: "Guernsey", label: "Guernsey" },
  { id: uuidv4(), value: "Guinea", label: "Guinea" },
  { id: uuidv4(), value: "Guinea-bissau", label: "Guinea-bissau" },
  { id: uuidv4(), value: "Guyana", label: "Guyana" },
  { id: uuidv4(), value: "Haiti", label: "Haiti" },
  {
    id: uuidv4(),
    value: "Heard Island and Mcdonald Islands",
    label: "Heard Island and Mcdonald Islands",
  },
  {
    id: uuidv4(),
    value: "Holy See (Vatican City State)",
    label: "Holy See (Vatican City State)",
  },
  { id: uuidv4(), value: "Honduras", label: "Honduras" },
  { id: uuidv4(), value: "Hong Kong", label: "Hong Kong" },
  { id: uuidv4(), value: "Hungary", label: "Hungary" },
  { id: uuidv4(), value: "Iceland", label: "Iceland" },
  { id: uuidv4(), value: "India", label: "India" },
  { id: uuidv4(), value: "Indonesia", label: "Indonesia" },
  {
    id: uuidv4(),
    value: "Iran, Islamic Republic of",
    label: "Iran, Islamic Republic of",
  },
  { id: uuidv4(), value: "Iraq", label: "Iraq" },
  { id: uuidv4(), value: "Ireland", label: "Ireland" },
  { id: uuidv4(), value: "Isle of Man", label: "Isle of Man" },
  { id: uuidv4(), value: "Israel", label: "Israel" },
  { id: uuidv4(), value: "Italy", label: "Italy" },
  { id: uuidv4(), value: "Jamaica", label: "Jamaica" },
  { id: uuidv4(), value: "Japan", label: "Japan" },
  { id: uuidv4(), value: "Jersey", label: "Jersey" },
  { id: uuidv4(), value: "Jordan", label: "Jordan" },
  { id: uuidv4(), value: "Kazakhstan", label: "Kazakhstan" },
  { id: uuidv4(), value: "Kenya", label: "Kenya" },
  { id: uuidv4(), value: "Kiribati", label: "Kiribati" },
  {
    id: uuidv4(),
    value: "Korea, Democratic People's Republic of",
    label: "Korea, Democratic People's Republic of",
  },
  { id: uuidv4(), value: "Korea, Republic of", label: "Korea, Republic of" },
  { id: uuidv4(), value: "Kuwait", label: "Kuwait" },
  { id: uuidv4(), value: "Kyrgyzstan", label: "Kyrgyzstan" },
  {
    id: uuidv4(),
    value: "Lao People's Democratic Republic",
    label: "Lao People's Democratic Republic",
  },
  { id: uuidv4(), value: "Latvia", label: "Latvia" },
  { id: uuidv4(), value: "Lebanon", label: "Lebanon" },
  { id: uuidv4(), value: "Lesotho", label: "Lesotho" },
  { id: uuidv4(), value: "Liberia", label: "Liberia" },
  {
    id: uuidv4(),
    value: "Libyan Arab Jamahiriya",
    label: "Libyan Arab Jamahiriya",
  },
  { id: uuidv4(), value: "Liechtenstein", label: "Liechtenstein" },
  { id: uuidv4(), value: "Lithuania", label: "Lithuania" },
  { id: uuidv4(), value: "Luxembourg", label: "Luxembourg" },
  { id: uuidv4(), value: "Macao", label: "Macao" },
  {
    id: uuidv4(),
    value: "Macedonia, The Former Yugoslav Republic of",
    label: "Macedonia, The Former Yugoslav Republic of",
  },
  { id: uuidv4(), value: "Madagascar", label: "Madagascar" },
  { id: uuidv4(), value: "Malawi", label: "Malawi" },
  { id: uuidv4(), value: "Malaysia", label: "Malaysia" },
  { id: uuidv4(), value: "Maldives", label: "Maldives" },
  { id: uuidv4(), value: "Mali", label: "Mali" },
  { id: uuidv4(), value: "Malta", label: "Malta" },
  { id: uuidv4(), value: "Marshall Islands", label: "Marshall Islands" },
  { id: uuidv4(), value: "Martinique", label: "Martinique" },
  { id: uuidv4(), value: "Mauritania", label: "Mauritania" },
  { id: uuidv4(), value: "Mauritius", label: "Mauritius" },
  { id: uuidv4(), value: "Mayotte", label: "Mayotte" },
  { id: uuidv4(), value: "Mexico", label: "Mexico" },
  {
    id: uuidv4(),
    value: "Micronesia, Federated States of",
    label: "Micronesia, Federated States of",
  },
  {
    id: uuidv4(),
    value: "Moldova, Republic of",
    label: "Moldova, Republic of",
  },
  { id: uuidv4(), value: "Monaco", label: "Monaco" },
  { id: uuidv4(), value: "Mongolia", label: "Mongolia" },
  { id: uuidv4(), value: "Montenegro", label: "Montenegro" },
  { id: uuidv4(), value: "Montserrat", label: "Montserrat" },
  { id: uuidv4(), value: "Morocco", label: "Morocco" },
  { id: uuidv4(), value: "Mozambique", label: "Mozambique" },
  { id: uuidv4(), value: "Myanmar", label: "Myanmar" },
  { id: uuidv4(), value: "Namibia", label: "Namibia" },
  { id: uuidv4(), value: "Nauru", label: "Nauru" },
  { id: uuidv4(), value: "Nepal", label: "Nepal" },
  { id: uuidv4(), value: "Netherlands", label: "Netherlands" },
  {
    id: uuidv4(),
    value: "Netherlands Antilles",
    label: "Netherlands Antilles",
  },
  { id: uuidv4(), value: "New Caledonia", label: "New Caledonia" },
  { id: uuidv4(), value: "New Zealand", label: "New Zealand" },
  { id: uuidv4(), value: "Nicaragua", label: "Nicaragua" },
  { id: uuidv4(), value: "Niger", label: "Niger" },
  { id: uuidv4(), value: "Nigeria", label: "Nigeria" },
  { id: uuidv4(), value: "Niue", label: "Niue" },
  { id: uuidv4(), value: "Norfolk Island", label: "Norfolk Island" },
  {
    id: uuidv4(),
    value: "Northern Mariana Islands",
    label: "Northern Mariana Islands",
  },
  { id: uuidv4(), value: "Norway", label: "Norway" },
  { id: uuidv4(), value: "Oman", label: "Oman" },
  { id: uuidv4(), value: "Pakistan", label: "Pakistan" },
  { id: uuidv4(), value: "Palau", label: "Palau" },
  {
    id: uuidv4(),
    value: "Palestinian Territory, Occupied",
    label: "Palestinian Territory, Occupied",
  },
  { id: uuidv4(), value: "Panama", label: "Panama" },
  { id: uuidv4(), value: "Papua New Guinea", label: "Papua New Guinea" },
  { id: uuidv4(), value: "Paraguay", label: "Paraguay" },
  { id: uuidv4(), value: "Peru", label: "Peru" },
  { id: uuidv4(), value: "Philippines", label: "Philippines" },
  { id: uuidv4(), value: "Pitcairn", label: "Pitcairn" },
  { id: uuidv4(), value: "Poland", label: "Poland" },
  { id: uuidv4(), value: "Portugal", label: "Portugal" },
  { id: uuidv4(), value: "Puerto Rico", label: "Puerto Rico" },
  { id: uuidv4(), value: "Qatar", label: "Qatar" },
  { id: uuidv4(), value: "Reunion", label: "Reunion" },
  { id: uuidv4(), value: "Romania", label: "Romania" },
  { id: uuidv4(), value: "Russian Federation", label: "Russian Federation" },
  { id: uuidv4(), value: "Rwanda", label: "Rwanda" },
  { id: uuidv4(), value: "Saint Helena", label: "Saint Helena" },
  {
    id: uuidv4(),
    value: "Saint Kitts and Nevis",
    label: "Saint Kitts and Nevis",
  },
  { id: uuidv4(), value: "Saint Lucia", label: "Saint Lucia" },
  {
    id: uuidv4(),
    value: "Saint Pierre and Miquelon",
    label: "Saint Pierre and Miquelon",
  },
  {
    id: uuidv4(),
    value: "Saint Vincent and The Grenadines",
    label: "Saint Vincent and The Grenadines",
  },
  { id: uuidv4(), value: "Samoa", label: "Samoa" },
  { id: uuidv4(), value: "San Marino", label: "San Marino" },
  {
    id: uuidv4(),
    value: "Sao Tome and Principe",
    label: "Sao Tome and Principe",
  },
  { id: uuidv4(), value: "Saudi Arabia", label: "Saudi Arabia" },
  { id: uuidv4(), value: "Senegal", label: "Senegal" },
  { id: uuidv4(), value: "Serbia", label: "Serbia" },
  { id: uuidv4(), value: "Seychelles", label: "Seychelles" },
  { id: uuidv4(), value: "Sierra Leone", label: "Sierra Leone" },
  { id: uuidv4(), value: "Singapore", label: "Singapore" },
  { id: uuidv4(), value: "Slovakia", label: "Slovakia" },
  { id: uuidv4(), value: "Slovenia", label: "Slovenia" },
  { id: uuidv4(), value: "Solomon Islands", label: "Solomon Islands" },
  { id: uuidv4(), value: "Somalia", label: "Somalia" },
  { id: uuidv4(), value: "South Africa", label: "South Africa" },
  {
    id: uuidv4(),
    value: "South Georgia and The South Sandwich Islands",
    label: "South Georgia and The South Sandwich Islands",
  },
  { id: uuidv4(), value: "Spain", label: "Spain" },
  { id: uuidv4(), value: "Sri Lanka", label: "Sri Lanka" },
  { id: uuidv4(), value: "Sudan", label: "Sudan" },
  { id: uuidv4(), value: "Suriname", label: "Suriname" },
  {
    id: uuidv4(),
    value: "Svalbard and Jan Mayen",
    label: "Svalbard and Jan Mayen",
  },
  { id: uuidv4(), value: "Swaziland", label: "Swaziland" },
  { id: uuidv4(), value: "Sweden", label: "Sweden" },
  { id: uuidv4(), value: "Switzerland", label: "Switzerland" },
  {
    id: uuidv4(),
    value: "Syrian Arab Republic",
    label: "Syrian Arab Republic",
  },
  { id: uuidv4(), value: "Taiwan", label: "Taiwan" },
  { id: uuidv4(), value: "Tajikistan", label: "Tajikistan" },
  {
    id: uuidv4(),
    value: "Tanzania, United Republic of",
    label: "Tanzania, United Republic of",
  },
  { id: uuidv4(), value: "Thailand", label: "Thailand" },
  { id: uuidv4(), value: "Timor-leste", label: "Timor-leste" },
  { id: uuidv4(), value: "Togo", label: "Togo" },
  { id: uuidv4(), value: "Tokelau", label: "Tokelau" },
  { id: uuidv4(), value: "Tonga", label: "Tonga" },
  { id: uuidv4(), value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
  { id: uuidv4(), value: "Tunisia", label: "Tunisia" },
  { id: uuidv4(), value: "Turkey", label: "Turkey" },
  { id: uuidv4(), value: "Turkmenistan", label: "Turkmenistan" },
  {
    id: uuidv4(),
    value: "Turks and Caicos Islands",
    label: "Turks and Caicos Islands",
  },
  { id: uuidv4(), value: "Tuvalu", label: "Tuvalu" },
  { id: uuidv4(), value: "Uganda", label: "Uganda" },
  { id: uuidv4(), value: "Ukraine", label: "Ukraine" },
  {
    id: uuidv4(),
    value: "United Arab Emirates",
    label: "United Arab Emirates",
  },
  { id: uuidv4(), value: "United Kingdom", label: "United Kingdom" },
  { id: uuidv4(), value: "United States", label: "United States" },
  {
    id: uuidv4(),
    value: "United States Minor Outlying Islands",
    label: "United States Minor Outlying Islands",
  },
  { id: uuidv4(), value: "Uruguay", label: "Uruguay" },
  { id: uuidv4(), value: "Uzbekistan", label: "Uzbekistan" },
  { id: uuidv4(), value: "Vanuatu", label: "Vanuatu" },
  { id: uuidv4(), value: "Venezuela", label: "Venezuela" },
  { id: uuidv4(), value: "Viet Nam", label: "Viet Nam" },
  {
    id: uuidv4(),
    value: "Virgin Islands, British",
    label: "Virgin Islands, British",
  },
  { id: uuidv4(), value: "Virgin Islands, U.S.", label: "irgin Islands, U.S." },
  { id: uuidv4(), value: "Wallis and Futuna", label: "Wallis and Futuna" },
  { id: uuidv4(), value: "Western Sahara", label: "Western Sahara" },
  { id: uuidv4(), value: "Yemen", label: "Yemen" },
  { id: uuidv4(), value: "Zambia", label: "Zambia" },
  { id: uuidv4(), value: "Zimbabwe", label: "Zimbabwe" },
];
